// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_9_studentsystem.dataasess;

#nullable disable

namespace task_9_studentsystem.Migrations
{
    [DbContext(typeof(studentDbContaxt))]
    partial class studentDbContaxtModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("task_9_studentsystem.model.course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseId"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("endDate")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("Varchar(80)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("startDate")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.HasKey("courseId");

                    b.HasIndex("studentId");

                    b.ToTable("coursees");
                });

            modelBuilder.Entity("task_9_studentsystem.model.homework", b =>
                {
                    b.Property<int>("homeworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("homeworkId"));

                    b.Property<string>("content")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("contentType")
                        .HasColumnType("int");

                    b.Property<int>("courseid")
                        .HasColumnType("int");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.Property<int>("submissonTime")
                        .HasColumnType("int");

                    b.HasKey("homeworkId");

                    b.HasIndex("courseid");

                    b.HasIndex("studentId");

                    b.ToTable("homeworkes");
                });

            modelBuilder.Entity("task_9_studentsystem.model.resource", b =>
                {
                    b.Property<int>("resourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("resourceId"));

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<int>("URL")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int>("courseid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("Varchar(50)");

                    b.HasKey("resourceId");

                    b.HasIndex("courseid");

                    b.ToTable("resourcees");
                });

            modelBuilder.Entity("task_9_studentsystem.model.student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentId"));

                    b.Property<DateTime?>("birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("phonenumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("registrediOn")
                        .HasColumnType("datetime2");

                    b.HasKey("studentId");

                    b.ToTable("studentes");
                });

            modelBuilder.Entity("task_9_studentsystem.model.course", b =>
                {
                    b.HasOne("task_9_studentsystem.model.student", "student")
                        .WithMany("courses")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("task_9_studentsystem.model.homework", b =>
                {
                    b.HasOne("task_9_studentsystem.model.course", "course")
                        .WithMany()
                        .HasForeignKey("courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task_9_studentsystem.model.student", "student")
                        .WithMany("homeworks")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("student");
                });

            modelBuilder.Entity("task_9_studentsystem.model.resource", b =>
                {
                    b.HasOne("task_9_studentsystem.model.course", "course")
                        .WithMany()
                        .HasForeignKey("courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");
                });

            modelBuilder.Entity("task_9_studentsystem.model.student", b =>
                {
                    b.Navigation("courses");

                    b.Navigation("homeworks");
                });
#pragma warning restore 612, 618
        }
    }
}
